name: Spellstorm Crusader CI / CD / CD

on:
  pull_request: {}
  push:
    branches:
      - '**'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  
jobs:
  buildWebGl:
    name: Build for WebGL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - BotAS
        unityVersion:
          - 6000.0.25f1
    steps:
      - name: Checkout the Repository
        id: checkout
        uses: actions/checkout@v4
        with:
          lfs: true     
      
      - uses: game-ci/unity-test-runner@v4
        id: myTestStep
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
      - uses: actions/upload-artifact@v4
        with:
          name: Build-WebGL
          path: build/WebGL
         
         
  deployPages:
    needs: buildWebGl
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: Build-WebGL
          path: build/WebGL
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: build/WebGL
